import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, RobustScaler
from sklearn.impute import SimpleImputer
from scipy.stats import mstats

In [1]:
# Adding the project root to the Python path
import sys
import os
sys.path.append(os.path.abspath(".."))

In [2]:
# Importing the preprocessing function from .py file
from scripts.data_preprocessing_script import preprocess_data

In [4]:
#Defining the path to dataset
data_source = '/Users/sawlehaanwaar/Documents/GitHub/life_expectancy_prediction_ml_model/data/raw/life_expectancy_data.csv'

In [5]:
# Running the preprocessing pipeline
df_processed = preprocess_data(data_source)

Data loaded: (2938, 22)
Step 1: Clean column names - done
Step 2: Convert column names to lowercase - done
Step 3: Encode categorical variables - done
Step 4: Impute missing values - done
Step 5: Transform skewed data - done
Step 6: Cap outliers - done
Step 7: Winsorize 'Percentage expenditure' - done
Preprocessing complete.

In [6]:
df_processed.head()

,country,year,life expectancy,adult mortality,infant deaths,alcohol,percentage expenditure,hepatitis b,measles,bmi,...,total expenditure,diphtheria,hiv/aids,gdp,population,thinness 1-19 years,thinness 5-9 years,income composition of resources,schooling,status_Developing
0,1.0,2015.0,65.0,263.0,7.874008,0.1,4.280542,3.555348,7.051856,19.1,...,8.16,65.0,0.09531,6.372055,17.334091,17.2,17.3,0.479,10.1,1.0
1,1.0,2014.0,59.9,271.0,8.000000,0.1,4.311116,3.637586,6.200509,18.6,...,8.18,62.0,0.09531,6.419501,12.699497,17.5,17.5,0.476,10.0,1.0
2,1.0,2013.0,59.9,268.0,8.124038,0.1,4.307023,3.583519,6.066108,18.1,...,8.13,64.0,0.09531,6.450067,17.272826,17.7,17.7,0.470,9.9,1.0
3,1.0,2012.0,59.5,272.0,8.306624,0.1,4.371777,3.496508,7.933080,17.6,...,8.52,67.0,0.09531,6.508708,15.123021,17.9,18.0,0.463,9.8,1.0
4,1.0,2011.0,59.2,275.0,8.426150,0.1,2.091507,3.465736,8.011023,17.2,...,7.87,68.0,0.09531,4.167242,14.906964,18.2,18.2,0.454,9.5,1.0